[greeter]
background=/usr/share/backgrounds/parrotos/wallpaper.png
theme-name=Greybird-dark
icon-theme-name=Papirus-Dark
font-name=Noto Sans 11
indicators=~host;~spacer;~clock;~spacer;~session;~language;~a11y;~power
clock-format=%A, %d. %B  %H:%M
user-background=false
